### ISSUE TITLE
Hello World!

### ISSUE THREAD

**Issue by starmaid** [mchartigan/bitwise#1]
We need to do a hello world for Firebase. I don't know anything. 

Things that need to be done:
- Someone creates a project on firebase
- Somehow gets a javascript file into their thing
- run the javascript program with node
- have the program send a webpage
- be able to view the webpage from any browser

**Comment by starmaid** [comment]
Someone mentioned Firebase being unable to deliver dynamic webpages. We have to figure out how to host one of those. This might include renting another server, or having two programs on the server that run concurrently. 

We might want to look into getting a domain name.

**Comment by mchartigan** [comment]
https://bitwise-a3c2d.web.app/
