### ISSUE TITLE
#3: Big brother is watching - View Account Info

### ISSUE THREAD

**Issue by zgeorge22** [mchartigan/bitwise#10]
As a user, I would like to be able to view my account information.

|# | Task Description | Time Estimate | Team | Owner|
|-- | -- | -- | -- | --|
|1 | Obtain user input for account information | 1 | Frontend | Zach G |
|2 | Send specific user information when requested | 2 | Backend | Zach G |
|3 | Design a display format for user information and input | 3 | Frontend | Zach G |
|4 | Verify acceptance criteria through unit testing | 1 | Frontend | Zach G, Kyle|

Acceptance Criteria
- Given that viewing account information has been implemented, when the user attempts to view their account information, then they will be redirected to an account information page.
- Given that viewing account information has been implemented, when the user is viewing their account information page, they should see their username, associated Google account email, bio, and picture.
- Given that viewing account information has been implemented, when the user is viewing their account information page, there should be a button to edit account information.

**Comment by mchartigan** [comment]
💯
