### ISSUE TITLE
#2: hacker voice im in - Logging into Accounts

### ISSUE THREAD

**Issue by starmaid** [mchartigan/bitwise#12]
# Logging into Accounts
As a user, I would like to be able to log in and out of my account on the website, authenticating my requests.

Num | Task Description | Time Estimate | Team | Owner
-- | -- | -- | -- | --
1 | Decide on website structure/hierarchy for users and main pages | 1 | Backend | Team
2 | Design a user login form | 4 | Frontend | Mark
3 | Obtain user info for login | 2 | Backend | Nick and Mark
4 | Set up Firebase data store for user login | 3 | Backend | Nick
5 | Upon login, fetch user profile information and send it to the frontend | 2 | Backend | Nick
6 | Create a homepage after logging in | 3 | Frontend | Nick
7 | Maintain login session across the site (Saving session token in cookies) | 2 | Frontend | Zach M
8 | Verify acceptance criteria through unit testing | 1 | Frontend | Zach M.

## Acceptance Criteria
- Given that login functionality has been implemented, when the user logs in using Google, they will be allowed to access login-required pages
- Given that a homepage has been developed, when the user logs in, they will be redirected there.
- Given that login functionality is robust, when the user navigates between pages or leaves the site for a short time, they will stay logged in.

**Comment by starmaid** [comment]
the "homepage" branch is where i just started doing work on this. I made the test homepage that gets all posts on the database regardless of login status

**Comment by mchartigan** [comment]
100% babey
