### ISSUE TITLE
Whats a Post? Whats a User?

### ISSUE THREAD

**Issue by starmaid** [mchartigan/bitwise#2]
This issue will involve deciding on how to store Users and Posts in the database. 

We will also need to consider how we will send these when requested by the frontend in a timely manner.

Whats a User? According to the class diagram, this includes: 
- id: int
- username: string
- email: string
- password: string
- posts: list<Post>
- following: list<User>
- followers: list<User>
- topics: list<Topic>
- upvotes: list<Post>
- downvotes: list<Post>
- saved: list<Post>

What components do we need in a post?
- id: int
- author: User
- content: String
- embed: Object
- creation_date: Date
- comments: list<Comment>
- topic: Topic
- upvotes: list<User>
- downvotes: list<User>

**Comment by mchartigan** [comment]
Done a while ago
