### ISSUE TITLE
The Most Basic Frontend

### ISSUE THREAD

**Issue by starmaid** [mchartigan/bitwise#4]
As javascript does not have a "print to stdout" function, all testing will have to be done in a browser. To test how posts and users look, we will have to create a very simple page that can display information retrieved from the server program, and thus, the database. 

### Pages needed:
- pure data display

### Later... (do not do, but keep in mind)
- User page
- Timeline
- "Create Post" Dialog
- Topic page

**Comment by mchartigan** [comment]
Deprecated
