### ISSUE TITLE
#4: Edit Your Stupid Profile Information into something better - Edit User Info

### ISSUE THREAD

**Issue by vandewak** [mchartigan/bitwise#7]
As a user, I would like to edit and save my account information.

|# | Task Description | Time Estimate | Team | Owner|
|-- | -- | -- | -- | --|
|1 | Design page for profile edit mode | 2 | Frontend | Zach G.|
|2 | Obtain user input for profile edits | 2 | Frontend | Kyle|
|3 | Validate edits to profile as acceptable (valid new username, proper characters) | 3 | Frontend | Kyle|
|4 | Modify database to store new user information | 4 | Backend | Kyle|
|5 | Retrieve updated user information to reflect changes | 3 | Frontend | Kyle|
|6 | Verify acceptance criteria through unit testing | 1 | Frontend | Kyle, Zach G.|

- Given that viewing account information has been implemented, when the user is viewing their account information page, there should be a button to edit account information.
- Given that editing account information has been implemented, when the user clicks the edit button, the existing information in the database should be pre-populated in the account fields prior to editing.
- Given that editing account information has been implemented, when the user saves their updated profile information, the newly edited account information should be visible in the database.
- Given that editing account information has been implemented, when the user saves their updated profile information, the updated account information should immediately be visible to all users.

**Comment by mchartigan** [comment]
As a result of PR #17 , authenticating on `public/js/profile.js` fails.

Error msg:
Uncaught TypeError: Cannot read property 'uid' of null
    at profile.js:5

(@zgeorge22)

**Comment by mchartigan** [comment]
fuckin done done
